### ISSUE TITLE
Join Wahoo?

### ISSUE THREAD

**Issue by bucaran** [mekanix/fish#4]
We are still relatively new in town, and just getting started, but we are more stable than the other options, namely OMF. I think some of these functions could be turned into a handful of Wahoo plugins or maybe some could be even make it to core. We are always accepting feature request and feedback. I would love if you could give [Wahoo](https://github.com/fish-shell/wahoo/blob/master/FAQ.md) a look.

Regards :smile:

**Comment by mekanix** [comment]
My config did grow a bit, so configuration management sounds right. If you feel like it, take any part of my config and include it where you like, and I'll spend some time checking out Wahoo.

**Comment by bucaran** [comment]
Sounds good! I'll look into that. Thanks for checking out Wahoo.

**Comment by bucaran** [comment]
Just got this notification. How are things?

**Comment by mekanix** [comment]
I'm testing fisherman in test account. I see you've been busy, which is nice to see. :o) What kind of contributions would you need the most for any of those two projects? Now that I'm healthy again, I'd like to contribute.

**Comment by bucaran** [comment]
fisherman and fin both have different designs, so it depends on which one do you like best. I think fisherman is more "pro", but I like fin more because it's simpler.

You could help of course just by trying out whichever you find more appealing. With regards to actual work / code, have a look at this [issue](https://github.com/fisherman/fisherman/issues/196).
